# -*- coding: utf-8 -*-
"""Task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lYsJfULR9zogBDFUFkWdrnK_GhBZEXBg
"""

import numpy as np
 import pandas as pd
 import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')
from google.colab import files
uploaded = files.upload()

population_df=pd.read_csv('/content/drive/My Drive/Total_Population.csv')
metadata_df = pd.read_csv('/content/drive/My Drive/Metadata_Country.csv')

population_df.head()

population_df.info()

metadata_df.head()

metadata_df.info()

population_df = population_df.drop(columns=['Indicator Name', 'Indicator Code','2023']).dropna()
metadata_df = metadata_df.drop(columns=['SpecialNotes', ]).dropna()
df = (population_df.merge(metadata_df, on='Country Code')
.rename(columns={'Country Name': 'Country', 'IncomeGroup':'Income'}))

df

df.to_csv ('/content/drive/My Drive/new_df.csv')

df.head()

df = df.melt(id_vars=['Country', 'Region', 'Income'],
value_vars=[str(year) for year in range(1960, 2023)],
var_name= 'Year',
value_name='Population')

df

df.to_csv ('/content/drive/My Drive/new01_df.csv')

df.head()

df.info()

df.duplicated().sum()

df.isna().sum()

